name: Print Software Versions
on:
 push:
  branches: LW4
jobs:
 PrintLanguageVersions:
      runs-on: ubuntu-latest
      steps:
         - name: Print Java Version
           run: java --version
         - name: Print Node Version
           run: node --version
         - name: Print Python Version
           run: python --version
 PrintDBMSVersions:
     runs-on: ubunt-latest
     needs: [PrintLanguageVersions]
     steps:
      - name: Print PostgresSQL Version
        run: psql --version
      - name: Print MySQL Version
        run: mysql -V
      - name: Print MongoDB Version
        run: mongo --version
