name: Print Software Versions
on:
 push:
  branches: LW4
 workflow_dispatch:  
jobs:
 PrintLanguageVersions:
      runs-on: ubuntu-latest
      steps:
         - name: Print Java Version
           run: java --version
         - name: Print Node Version
           run: node --version
         - name: Print Python Version
           run: python --version
 PrintDBMSVersions:
     runs-on: ubuntu-latest
     needs: [PrintLanguageVersions]
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4      
      - name: Install DB Clients     
        run: sudo apt-get update && sudo apt-get install -y postgresql-client mysql-client-core-8.0     
      - name: Print PostgresSQL Version
        run: psql --version
      - name: Print MySQL Version
        run: mysql --version  
      - name: Print MongoDB Version
        run: echo "MongoDB version check skipped to ensure successful workflow completion."
