name: Program Code Convention Check (Java)

on:
  push:
    branches: [ LW4 ] 
  workflow_dispatch:

jobs:
  lint-java-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java Environment
        
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Download Checkstyle JAR
        
        run: |
          CHECKSTYLE_VERSION=10.12.5 # Актуальна версія
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-${CHECKSTYLE_VERSION}/checkstyle-${CHECKSTYLE_VERSION}-all.jar -O checkstyle.jar
          
     
      - name: Check ProgramCode.java for conventions
        run: |
          echo "Starting convention check on ProgramCode.java..."
       
          java -jar checkstyle.jar -c /sun_checks.xml ProgramCode.java || true
          
     
      - name: Check ProgramCodeModified.java for conventions
        run: |
          echo "Starting convention check on ProgramCodeModified.java..."
          java -jar checkstyle.jar -c /sun_checks.xml ProgramCodeModified.java || true
          
     
